### ISSUE TITLE
NullpointerException in TwintFlowFragment (Test)                                                                                	

### ISSUE THREAD

**Issue by andreaMOnline** [datatrans/android-sdk#13]
A crash happens with:
Datatrans Mobile SDK 3.1.0 (Android 12/target=33)
Datatrans Mobile SDK 3.1.1 (Android 12/target=33)
Datatrans Mobile SDK 3.1.0 (Android 13/target=33)
Datatrans Mobile SDK 3.1.1 (Android 13/target=33)

During viewModel creation of TwintFlowFragment in
ch.datatrans.payment.bottomsheet.TransactionSheetActivity

Twint Configurable 36.1.0.1/37.0.018 is installed on PAT environment

Crash Details:
`java.lang.NullPointerException
            at a.a.a.p.h.b.<init>(SourceFile:18)
            at a.a.a.p.h.f.create(SourceFile:2)
            at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.kt:83)
            at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:187)
            at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:153)
            at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:53)
            at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
            at a.a.a.p.h.a.c(SourceFile:1)
            at a.a.a.p.h.a.d(SourceFile:1)
            at a.a.a.p.h.a.onActivityCreated(SourceFile:3)
           at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3156)
           at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:619)
           at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
           at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
          at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
           at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
          at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
          at android.os.Handler.handleCallback(Handler.java:938)
          at android.os.Handler.dispatchMessage(Handler.java:99)
         at android.os.Looper.loopOnce(Looper.java:226)
          at android.os.Looper.loop(Looper.java:313)
          at android.app.ActivityThread.main(ActivityThread.java:8751)
         at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

Recording:
[pixel_6_API33_recording.webm](https://github.com/datatrans/android-sdk/assets/138590682/b6739379-c311-40d8-8470-f074e6e7db83)

**Comment by luiscosta** [comment]
Hello @andreaMOnline,

Can you give us a mobileToken for that exception? 

Thank you!

**Comment by andreaMOnline** [comment]
> Hello @andreaMOnline,
> 
> Can you give us a mobileToken for that exception?
> 
> Thank you!

here you go:
02fdf1e56c0a7e9f70df78d926a875700333a1fcfe9bcc1f

**Comment by jschmid** [comment]
We have the same issue.

Token `1dbe955feb31e5a0c0e0b502809fdbfd0333a2044e20b8b2`

**Comment by luiscosta** [comment]
Hello @andreaMOnline and @jschmid,

Just to be sure we are talking about the same issue, can you please test the following version to see if it fixes it for you?

Version: "1.0.0-TwintFix311"

Thank you!

**Comment by jschmid** [comment]
@luiscosta yes it works fine now. Thanks!

Do you have a rough idea about the release time? To know if we should stop our upgrade attempt, or only postpone it for a few days.

**Comment by luiscosta** [comment]
Hello @jschmid,

Thank you for confirming it!

This will be added on the next version and it will most likely be released next week.

**Comment by luiscosta** [comment]
Hello @andreaMOnline and @jschmid,

The version 3.2.0 is released and this issue is resolved!

You can find it on our new jfrog: https://weareplanet.jfrog.io/artifactory/mobile-sdk/

Thank you for your patience!

**Comment by luiscosta** [comment]
Hello @andreaMOnline, @jschmid,

We moved back the SDK to the previous link, so please update the link to https://datatrans.jfrog.io/ui/native/mobile-sdk/

The previous one **will stop working after Thursday 27th**.
