### ISSUE TITLE
Crash after launching data trans transaction

### ISSUE THREAD

**Issue by okalman** [datatrans/android-sdk#19]
Hello, we have recently deployed DataTrans SDK into production and we can see two crashes in our crashlytics (but both are very rare)

**First: Samsung Galaxy M34 (Android 12)**
`Fatal Exception: java.lang.IllegalStateException: Fragment m{16f7760} (95f184f7-9430-4af6-a2f8-5fc62ab76bbe) not attached to an activity.
       at androidx.fragment.app.Fragment.requireActivity(Fragment.java:995)
       at a.a.a.j.n.a.b(SourceFile:3)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)`

**Second: Redmi Note 10 Pro (Android 13)**
`Fatal Exception: java.lang.NullPointerException:
       at a.a.a.j.d.e(SourceFile:34)
       at a.a.a.j.d.onViewCreated(SourceFile:2)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1424)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2968)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2886)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1564)
       at android.app.Activity.performStart(Activity.java:8555)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3859)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:211)
       at android.os.Looper.loop(Looper.java:300)
       at android.app.ActivityThread.main(ActivityThread.java:8296)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)`

Both crashes were encountered on version 3.2.0
Since the code is obfuscated we have no clue what's wrong so I'm sending it to you for further investigation (if you are interested).

**Comment by bacherma** [comment]
Presumably fixed in newer release.
