### ISSUE TITLE
Visa/Mastercard payment crash with 2.3.1

### ISSUE THREAD

**Issue by Kevinrob** [datatrans/android-sdk#6]
Hi,

We got a crash with the version 2.3.1 when we try to pay with Visa or Mastercard:
```
E  FATAL EXCEPTION: main
Process: ch.alpsoft.qoqa.ui.debug, PID: 14520
java.lang.NullPointerException: findViewById(R.id.list) must not be null
	at ch.datatrans.payment.bottomsheet.TransactionSheetActivity.a(SourceFile:425)
	at ch.datatrans.payment.bottomsheet.TransactionSheetActivity$$ExternalSyntheticLambda3.onChanged(Unknown Source:6)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by bacherma** [comment]
Hi @Kevinrob, thanks for letting us know. It happened in some cases with preselected payment methods. Fixed in 2.3.2 ([link](https://github.com/datatrans/android-sdk/releases/tag/2.3.2)).
